version: "3.9"
services:
    db:
        image: mysql
        container_name: db
        ports:
            - "1143:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
            MYSQL_DATABASE: "enem_db"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "1234"
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
          - my_network

networks:
  my_network:
    driver: bridge